[package]
name = "frontier-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dotenvy = "0.15"
frontier-shared = { path = "../shared" }
sqlx = { version = "0.9", default-features = false, features = ["postgres", "runtime-tokio", "tls-rustls"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
